title: "SIEAT.net"
description: Security Immersion Experience Austria
remote_theme: pmarsceill/just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/banner_sieatnet_flag.png"

# Color scheme currently only supports "dark" or nil (default)
#color_scheme: nil

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Footer content appears at the bottom of every page's main content
footer_content: "Content put together by Markus Schellenberger and Klaus Harrer-Nemecek.<br>Page Layout &copy; 2017-2019 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"

